name: encord-maskrcnn
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.8
  - pip=23.0
  - python=3.11.0
  - readline=8.1.2
  - setuptools=67.1.0
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - alembic==1.12.0
    - anyio==4.0.0
    - appdirs==1.4.4
    - av==10.0.0
    - cachetools==5.3.1
    - certifi==2023.7.22
    - cffi==1.15.1
    - charset-normalizer==3.2.0
    - click==8.1.7
    - clip-ea==1.0
    - commonmark==0.9.1
    - contourpy==1.1.1
    - cryptography==41.0.4
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - encord==0.1.95
    - encord-active==0.1.76
    - fastapi==0.95.2
    - filelock==3.12.4
    - fonttools==4.42.1
    - ftfy==6.1.1
    - gitdb==4.0.10
    - gitpython==3.1.37
    - greenlet==2.0.2
    - h11==0.14.0
    - httpcore==0.18.0
    - httptools==0.6.0
    - httpx==0.25.0
    - idna==3.4
    - inquirerpy==0.3.4
    - jinja2==3.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - kornia==0.6.12
    - lightning-utilities==0.9.0
    - llvmlite==0.40.1
    - loguru==0.6.0
    - mako==1.2.4
    - markupsafe==2.1.3
    - matplotlib==3.8.0
    - mpmath==1.3.0
    - multimethod==1.10
    - mypy-extensions==1.0.0
    - natsort==8.4.0
    - networkx==3.1
    - nodeenv==1.8.0
    - nodejs-bin==16.15.1a4
    - numba==0.57.1
    - numpy==1.23.5
    - opencv-python==4.5.5.64
    - orjson==3.9.7
    - packaging==23.1
    - pandas==1.5.3
    - pandas-stubs==2.0.1.230501
    - pandera==0.15.2
    - pastel==0.2.1
    - pathtools==0.1.2
    - pfzy==0.3.4
    - pillow==10.0.1
    - plotly==5.17.0
    - poethepoet==0.16.5
    - prisma==0.8.2
    - prompt-toolkit==3.0.39
    - protobuf==4.24.3
    - psutil==5.9.5
    - pycocotools==2.0.7
    - pycparser==2.21
    - pydantic==1.10.12
    - pygments==2.16.1
    - pyjwt==2.8.0
    - pynndescent==0.5.10
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - python-dotenv==0.21.1
    - python-multipart==0.0.6
    - pytz==2022.7.1
    - pyyaml==6.0.1
    - regex==2023.8.8
    - requests==2.31.0
    - rich==12.6.0
    - scikit-learn==1.3.1
    - scipy==1.10.1
    - sentry-sdk==1.31.0
    - setproctitle==1.3.2
    - shapely==1.8.5.post1
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - sqlalchemy==1.4.41
    - sqlalchemy2-stubs==0.0.2a35
    - sqlmodel==0.0.8
    - starlette==0.27.0
    - sympy==1.12
    - tbb==2021.10.0
    - tenacity==8.2.3
    - termcolor==2.3.0
    - threadpoolctl==3.2.0
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.12.1
    - torch==2.0.1
    - torchmetrics==1.2.0
    - torchvision==0.15.2
    - tqdm==4.66.1
    - typeguard==4.1.5
    - typer==0.6.1
    - types-cachetools==5.3.0.6
    - types-pytz==2022.7.1.2
    - typing-extensions==4.8.0
    - typing-inspect==0.9.0
    - umap-learn==0.5.4
    - urllib3==2.0.5
    - uvicorn==0.21.1
    - uvloop==0.17.0
    - wandb==0.15.11
    - watchdog==2.3.1
    - watchfiles==0.20.0
    - wcwidth==0.2.6
    - websockets==11.0.3
    - wrapt==1.15.0